### ISSUE TITLE
rspec 2.6.0.rc3 gemspec causes exceptions in rubygems 1.3.7

### ISSUE THREAD

**Issue by indirect** [rspec/rspec-core#358]
Hello!

The gemspec for the 2.6.0.rc3 gem has invalid data in it. Specifically, the dependency lines that look like this:

```
s.add_runtime_dependency(%q<rspec-core>, ["#<YAML::Syck::DefaultKey:0x1069613b8> 2.6.0.rc3"])
```

When it tries to do stuff with that gemspec, Rubygems 1.3.7 just explodes. As a result, it is impossible to install 2.6.0.rc3 using that Rubygems version:

```
$ gem install rspec --pre
ERROR:  While executing gem ... (NoMethodError)
   undefined method `call' for nil:NilClass
```

It is also impossible to run `bundle install` against any Gemfile that requires any rspec prerelease version, because Bundler will evaluate the gemspec and call some Rubygems methods that result in an exception due to the invalid data.

Please fix the gemspec so that rspec will still work with Rubygems 1.3.7! Thanks.
