### ISSUE TITLE
Rspec 2.99.0, Zeus, Shoulda

### ISSUE THREAD

**Issue by nathany** [rspec/rspec-core#1567]
When upgrading from RSpec 2.99.0rc1 to 2.99.0 or 3.0.0 I'm seeing test failures, but only when running under Zeus:

```
Failure/Error: it { should validate_numericality_of(:cost) }
     NoMethodError:
       undefined method `validate_numericality_of' for #<RSpec::Core::ExampleGroup::Nested_56:0x000001167697d0>
```

This is with zeus (0.13.3) and shoulda-matchers (2.6.1). We are on an older version of zeus do to zeus-parallel_tests (0.2.4).

An idea what would have changed to cause shoulda matchers to not be defined?
