### ISSUE TITLE
undefined method `validate_numericality_of`

### ISSUE THREAD

**Issue by 8vius** [rspec/rspec-core#2157]
I'm getting this error when running some specs 

```
Failure/Error: should validate_numericality_of(:minutes_worked).
     NoMethodError:
       undefined method `validate_numericality_of' for #<RSpec::ExampleGroups::Service:0x007f9aedaec380>
```

My shoulda-matchers version is 3.1.0. Any idea what might be the issue?

**Comment by trushkevich** [comment]
I face this error after upgrading to 3.1.1, but when I downgrade  back to 2.8.0 the error goes away.
