### ISSUE TITLE
2.0.0.beta.16 breaks with Spork

### ISSUE THREAD

**Issue by mhartl** [rspec/rspec-core#61]
Running the `rspec` script (or `autotest`) with a Spork server works fine in 2.0.0.beta.15, but it breaks in 2.0.0.beta.16. The error when running `rspec` is as follows:

```
Exception encountered: #<NoMethodError: undefined method `configure' for ["--color", "spec"]:Array>
backtrace:
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/rspec-core-2.0.0.beta.16/lib/rspec/core/command_line.rb:11:in `run'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/rspec-core-2.0.0.beta.16/lib/rspec/monkey/spork/test_framework/rspec.rb:4:in `run_tests'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/run_strategy/forking.rb:13:in `block in run'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/forker.rb:21:in `block in initialize'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/forker.rb:18:in `fork'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/forker.rb:18:in `initialize'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/run_strategy/forking.rb:9:in `new'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/run_strategy/forking.rb:9:in `run'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/server.rb:47:in `run'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1558:in `perform_without_block'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1518:in `perform'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1592:in `block (2 levels) in main_loop'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1588:in `loop'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1588:in `block in main_loop'
```

When running `autotest`, it's slightly different:

```
Exception encountered: #<NoMethodError: undefined method `configure' for #<Array:0x295fa68>>
backtrace:
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/rspec-core-2.0.0.beta.16/lib/rspec/core/command_line.rb:11:in `run'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/rspec-core-2.0.0.beta.16/lib/rspec/monkey/spork/test_framework/rspec.rb:4:in `run_tests'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/run_strategy/forking.rb:13:in `block in run'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/forker.rb:21:in `block in initialize'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/forker.rb:18:in `fork'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/forker.rb:18:in `initialize'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/run_strategy/forking.rb:9:in `new'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/run_strategy/forking.rb:9:in `run'
/Users/mhartl/.rvm/gems/ruby-1.9.2-rc1@sample_app/gems/spork-0.8.4/lib/spork/server.rb:47:in `run'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1558:in `perform_without_block'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1518:in `perform'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1592:in `block (2 levels) in main_loop'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1588:in `loop'
/Users/mhartl/.rvm/rubies/ruby-1.9.2-rc1/lib/ruby/1.9.1/drb/drb.rb:1588:in `block in main_loop'
```

The contents of the `.rspec` file in both cases are the same:

```
--colour
--drb
```
