### ISSUE TITLE
NameError in rspec-core-2.14.1/lib/rspec/core/reporter.rb

### ISSUE THREAD

**Issue by znz** [rspec/rspec-core#968]
rspec-core-2.14.1 does not work with ci_reporter-1.9.0.

```
% bundle exec rake -f $(bundle show ci_reporter)/stub.rake ci:setup:rspec default
rm -rf spec/reports
/Users/kazu/.rbenv/versions/1.9.3-p429/bin/ruby -S rspec
/private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/reporter.rb:134:in `method': undefined method `start' for class `CI::Reporter::RSpec' (NameError)
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/reporter.rb:134:in `understands'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/reporter.rb:24:in `block in register_listener'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/reporter.rb:23:in `each'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/reporter.rb:23:in `register_listener'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/reporter.rb:10:in `block in initialize'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/reporter.rb:9:in `each'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/reporter.rb:9:in `initialize'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/configuration.rb:591:in `new'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/configuration.rb:591:in `reporter'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/world.rb:62:in `reporter'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/world.rb:88:in `announce_filters'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/command_line.rb:23:in `run'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/runner.rb:80:in `run'
    from /private/tmp/foo/vendor/bundle/ruby/1.9.1/gems/rspec-core-2.14.1/lib/rspec/core/runner.rb:17:in `block in autorun'
/Users/kazu/.rbenv/versions/1.9.3-p429/bin/ruby -S rspec failed
% cat Gemfile      
source 'https://rubygems.org'
gem 'rails', '3.2.13'
gem 'sqlite3'
group :development, :test do
  gem 'rspec-rails'
end
gem 'ci_reporter', require: false, group: :test
% bundle list
Gems included by the bundle:
  * actionmailer (3.2.13)
  * actionpack (3.2.13)
  * activemodel (3.2.13)
  * activerecord (3.2.13)
  * activeresource (3.2.13)
  * activesupport (3.2.13)
  * arel (3.0.2)
  * builder (3.0.4)
  * bundler (1.3.5)
  * ci_reporter (1.9.0)
  * diff-lcs (1.2.4)
  * erubis (2.7.0)
  * hike (1.2.3)
  * i18n (0.6.1)
  * journey (1.0.4)
  * json (1.8.0)
  * mail (2.5.4)
  * mime-types (1.23)
  * multi_json (1.7.7)
  * polyglot (0.3.3)
  * rack (1.4.5)
  * rack-cache (1.2)
  * rack-ssl (1.3.3)
  * rack-test (0.6.2)
  * rails (3.2.13)
  * railties (3.2.13)
  * rake (10.1.0)
  * rdoc (3.12.2)
  * rspec-core (2.14.1)
  * rspec-expectations (2.14.0)
  * rspec-mocks (2.14.1)
  * rspec-rails (2.14.0)
  * sprockets (2.2.2)
  * sqlite3 (1.3.7)
  * thor (0.18.1)
  * tilt (1.4.1)
  * treetop (1.4.14)
  * tzinfo (0.3.37)
```
