### ISSUE TITLE
RSpec 2.6 fails under MacRuby; 2.5 is OK

### ISSUE THREAD

**Issue by sjmadsen** [rspec/rspec-core#461]
I'm running RSpec under MacRuby 0.10. Everything works nicely with RSpec 2.5. When I update the gems to 2.6, though, I get `undefined method 'empty?' for #<Enumerator:0x40093ee00> (NoMethodError)` at startup and none of the examples run.

The full error backtrace follows.

```
/Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/Gems/1.9.2/gems/rspec-core-2.6.4/lib/rspec/core/world.rb:14:in `empty_without_conditional_filters?': undefined method `empty?' for #<Enumerator:0x40093ee00> (NoMethodError)
    from /Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/Gems/1.9.2/gems/rspec-core-2.6.4/lib/rspec/core/world.rb:131:in `announce_exclusion_filter:'
    from /Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/Gems/1.9.2/gems/rspec-core-2.6.4/lib/rspec/core/world.rb:103:in `announce_filters'
    from /Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/Gems/1.9.2/gems/rspec-core-2.6.4/lib/rspec/core/command_line.rb:19:in `run:'
    from /Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/Gems/1.9.2/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:80:in `run_in_process:'
    from /Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/Gems/1.9.2/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:69:in `run:'
    from /Library/Frameworks/MacRuby.framework/Versions/0.10/usr/lib/ruby/Gems/1.9.2/gems/rspec-core-2.6.4/lib/rspec/core/runner.rb:11:in `block'
```
