### PR TITLE
Fix `BacktraceFormatter` to handle `nil` backtraces.

### LINKED ISSUE #2117: Error from #format_backtrace blows up rest of suite
I'm getting the following error which crashes the rest of the test suite:

gems/ruby/2.0.0/gems/rspec-core-3.4.0/lib/rspec/core/backtrace_formatter.rb:34:in 'format_backtrace': undefined method 'empty?' for nil:NilClass (NoMethodError)

The `empty?` call was introduced by [this commit](https://github.com/rspec/rspec-core/commit/48db9020b714ac5a37cac52bf7e47bc8de27c5d2).

### PR DESCRIPTION
**Pull request by myronmarston**
`Exception.new.backtrace` is `nil` so we can't count on
there always being a backtrace. Before now we relied
on the `format_backtrace` caller handling this (passing
`ex.backtrace || []`), but with #2074 now also including
the `exception.cause` in failure output, the code there
did not guard the `format_backtrace` call with `|| []`
and is causing users to get a `NoMethodError`. It's
easiest if `format_backtrace just handles the `nil` case
so each caller does not have to remember to handle it.

Fixes #2117.

### CODE REVIEW

**Comment by JonRowe** [comment]
LGTM and its :green_book: :)

**Comment by mrageh** [comment]
@myronmarston thank you for fixing #2117, but I really don't understand how the `BacktraceFormatter#format_backtrace` gets `nil` instead of an empty array. 

The way I understood this code was we passed an empty array when the `Exception#backtrace` returns `nil`. Since we passed it an empty array `BacktraceFormatter#format_backtrace` would return the `Exception#backtrace` which in this case was `nil`. Then the code `ExceptionPresenter#formatted_backtrace` should try to execute `nil + formatted_cause(exception)` and the error `NoMethodError: undefined method `+' for nil:NilClass` should really be happening there right? 

Can you please explain how I've misunderstood this?

**Comment by myronmarston** [comment]
`BacktraceFormatter#format_backtrace` should not return `nil` in any circumstances.  It should always return an array.  Before 3.4.0, it had exactly one call site:

https://github.com/rspec/rspec-core/blob/v3.3.2/lib/rspec/core/formatters/exception_presenter.rb#L34

This was never `nil` because `exception_backtrace` guarded against this, passing an empty array instead:

https://github.com/rspec/rspec-core/blob/v3.3.2/lib/rspec/core/formatters/exception_presenter.rb#L150-L152

So in RSpec 3.3.x, `format_backtrace` always received an array and always returned an array.  However, it worked only because the caller was required to guard against `nil` with a `exception.backtrace || []` expression, which was unfortunately easy to forget.

In 3.4.0, the bug was introduced by #2074, which, among other things, added [this bit of code](https://github.com/rspec/rspec-core/pull/2074/files#diff-e3d4254ff910a5de5bcf2ff439e2d62eR53):

``` ruby
cause << ("  #{backtrace_formatter.format_backtrace(last_cause.backtrace, example.metadata).first}")
```

Here `last_cause.backtrace` is being passed to `format_backtrace`.  Notice that there's not the `|| []` bit required of the caller to guard against nil.  While I didn't have a full stack trace from #2117 to show this as the callsite where it was blowing up, I reasoned my way there because the error reported in #2117 was:

> gems/ruby/2.0.0/gems/rspec-core-3.4.0/lib/rspec/core/backtrace_formatter.rb:34:in 'format_backtrace': undefined method 'empty?' for nil:NilClass (NoMethodError)

...which means that `format_backtrace` was being passed `nil` from some caller, and we have only two callsites.  One callsite guards against `nil` (passing `[]` instead) and one does not, so logically, the problem must have been with the one that does not (e.g. `format_backtrace(last_cause.backtrace, ...)`).

In this PR I could have fixed it by adding `|| []` to this callsite but I realized that there was a deeper cause: `format_backtrace` required its callers to consider `nil` as a possibility and handle it, but that is not something a caller is likely to think of!  It's far easier to instead accept `nil`.

Does that help, @mrageh?

**Comment by mrageh** [comment]
Thanks @myronmarston yes that's very helpful in fact I forgot I used `format_backtrace` in my pr :laughing:
